[tool]
id = "com.dailyhobbyist.bible"
label = "Bible"
versionCode = 4
versionName = "1.3"
permissions = ["android.permission.INTERNET"]
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
