[tool]
id = "com.dailyhobbyist.bible"
label = "Bible"
versionCode = 11
versionName = "2.0"
permissions = ["android.permission.INTERNET"]
# change to com.thelightphone.sdk.emulator if you run this on the SDK emulator
serverPackage = "com.lightos"
